jobs:
 build:
   machine: true
   steps:
     - checkout

     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

     # build the application image
     - run: docker build -t sjmyuan/nextcloud-ffmpeg:$CIRCLE_BRANCH -t sjmyuan/nextcloud-ffmpeg:latest -t sjmyuan/nextcloud-ffmpeg .

     # deploy the image
     - run: docker push --all-tags sjmyuan/nextcloud-ffmpeg
version: 2.1
